apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://localhost:9090
    access: proxy
    isDefault: false
    editable: true
    
  - name: Jaeger
    type: jaeger
    uid: jaeger
    url: http://localhost:16686
    access: proxy
    editable: true
    isDefault: true